development:
  sessions:
    default:
      database: scrooge_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:  
test:
  sessions:
    default:
      database: scrooge_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
<% if ENV['MONGOHQ_URL'] %>
  <% uri = URI.parse(ENV['MONGOHQ_URL']) %>
production:
  sessions:
    default:
      database: <%= uri.path.sub('/','') %>
      username: <%= uri.user %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
<% end %>
